# Generated by Django 5.2.7 on 2025-10-16 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CausaMerma',
            fields=[
                ('id_causa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_causa', models.CharField(max_length=100, verbose_name='Nombre de la Causa')),
            ],
            options={
                'verbose_name': 'Causa de Merma',
                'verbose_name_plural': 'Causas de Merma',
                'db_table': 'CAUSA_MERMA',
                'ordering': ['nombre_causa'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_insumo', models.CharField(max_length=100, verbose_name='Nombre del Insumo')),
                ('unidad_medida', models.CharField(max_length=50, verbose_name='Unidad de Medida')),
                ('costo_promedio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Promedio')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'db_table': 'INSUMO',
                'ordering': ['nombre_insumo'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id_orden_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField(verbose_name='Fecha del Pedido')),
                ('estado', models.CharField(default='pendiente', max_length=50, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'db_table': 'ORDEN_COMPRA',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id_plato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plato', models.CharField(max_length=120, verbose_name='Nombre del Plato')),
            ],
            options={
                'verbose_name': 'Plato',
                'verbose_name_plural': 'Platos',
                'db_table': 'PLATO',
                'ordering': ['nombre_plato'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=120, verbose_name='Nombre del Proveedor')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'PROVEEDOR',
                'ordering': ['nombre_proveedor'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50, verbose_name='Nombre del Rol')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'ROL',
                'ordering': ['nombre_rol'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ubicacion', models.CharField(max_length=100, verbose_name='Nombre de la Ubicación')),
                ('tipo_ubicacion', models.CharField(max_length=50, verbose_name='Tipo de Ubicación')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'UBICACION',
                'ordering': ['nombre_ubicacion'],
            },
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='unidad_medida',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='usuario_creacion',
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_detalle_compra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_pedida', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Pedida')),
                ('costo_unitario_acordado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Unitario')),
                ('id_insumo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.insumo', verbose_name='Insumo')),
                ('id_orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ordencompra', verbose_name='Orden de Compra')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compra',
                'db_table': 'DETALLE_COMPRA',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Unitario')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('cantidad_actual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Actual')),
                ('id_detalle_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.detallecompra', verbose_name='Detalle de Compra')),
                ('id_insumo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.insumo', verbose_name='Insumo')),
                ('id_ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.ubicacion', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'db_table': 'LOTE',
                'ordering': ['fecha_vencimiento', 'fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='PrediccionDemanda',
            fields=[
                ('id_prediccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_prediccion', models.DateField(verbose_name='Fecha de Predicción')),
                ('cantidad_pronosticada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Pronosticada')),
                ('id_plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.plato', verbose_name='Plato')),
            ],
            options={
                'verbose_name': 'Predicción de Demanda',
                'verbose_name_plural': 'Predicciones de Demanda',
                'db_table': 'PREDICCION_DEMANDA',
                'ordering': ['-fecha_prediccion'],
            },
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.proveedor', verbose_name='Proveedor'),
        ),
        migrations.CreateModel(
            name='EvaluacionProveedor',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('criterio', models.CharField(max_length=100, verbose_name='Criterio')),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Puntaje')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Evaluación de Proveedor',
                'verbose_name_plural': 'Evaluaciones de Proveedores',
                'db_table': 'EVALUACION_PROVEEDOR',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_receta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_necesaria', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Necesaria')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('id_insumo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.insumo', verbose_name='Insumo')),
                ('id_plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.plato', verbose_name='Plato')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'db_table': 'RECETA',
                'unique_together': {('id_plato', 'id_insumo')},
            },
        ),
        migrations.CreateModel(
            name='RegistroVentaPlato',
            fields=[
                ('id_venta_plato', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField(verbose_name='Fecha de Venta')),
                ('cantidad_vendida', models.IntegerField(verbose_name='Cantidad Vendida')),
                ('id_plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.plato', verbose_name='Plato')),
            ],
            options={
                'verbose_name': 'Venta de Plato',
                'verbose_name_plural': 'Ventas de Platos',
                'db_table': 'REGISTRO_VENTA_PLATO',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVentaIns',
            fields=[
                ('id_detalle_venta_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_usada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Usada')),
                ('id_lote', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.lote', verbose_name='Lote')),
                ('id_venta_plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.registroventaplato', verbose_name='Venta de Plato')),
            ],
            options={
                'verbose_name': 'Detalle de Venta de Insumo',
                'verbose_name_plural': 'Detalles de Venta de Insumos',
                'db_table': 'DETALLE_VENTA_INS',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password_hash', models.CharField(max_length=128, verbose_name='Hash de Contraseña')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.rol', verbose_name='Rol')),
                ('user_django', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Django')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'USUARIO',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_movimiento', models.DateField(verbose_name='Fecha de Movimiento')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('transferencia', 'Transferencia'), ('ajuste', 'Ajuste')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('origen_movimiento', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta'), ('merma', 'Merma'), ('prediccion', 'Predicción'), ('manual', 'Manual')], max_length=20, verbose_name='Origen del Movimiento')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('id_lote', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.lote', verbose_name='Lote')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'db_table': 'MOVIMIENTO_STOCK',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='Merma',
            fields=[
                ('id_merma', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(verbose_name='Fecha de Registro')),
                ('cantidad_desperdiciada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Desperdiciada')),
                ('id_causa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.causamerma', verbose_name='Causa')),
                ('id_lote', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.lote', verbose_name='Lote')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Merma',
                'verbose_name_plural': 'Mermas',
                'db_table': 'MERMA',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.DeleteModel(
            name='CategoriaProducto',
        ),
        migrations.DeleteModel(
            name='UnidadMedida',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
