# Generated by Django 5.2.7 on 2025-11-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_categoriaproducto_unidadmedida'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='correo_proveedor',
            field=models.EmailField(blank=True, default='', max_length=50, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion_proveedor',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono_proveedor',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Teléfono'),
        ),
    ]
