# Generated by Django 5.2.7 on 2025-11-05 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_proveedor_correo_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='id_insumo',
            field=models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.RESTRICT, to='inventario.insumo', verbose_name='Insumo'),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='id_orden_compra',
            field=models.ForeignKey(db_column='id_orden_compra', on_delete=django.db.models.deletion.CASCADE, to='inventario.ordencompra', verbose_name='Orden de Compra'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='id_detalle_compra',
            field=models.ForeignKey(db_column='id_detalle_compra', on_delete=django.db.models.deletion.CASCADE, to='inventario.detallecompra', verbose_name='Detalle de Compra'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='id_insumo',
            field=models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.RESTRICT, to='inventario.insumo', verbose_name='Insumo'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='id_ubicacion',
            field=models.ForeignKey(db_column='id_ubicacion', on_delete=django.db.models.deletion.RESTRICT, to='inventario.ubicacion', verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.RESTRICT, to='inventario.proveedor', verbose_name='Proveedor'),
        ),
    ]
