# Generated by Django 5.2.7 on 2025-11-06 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_detallecompra_id_insumo_and_more'),
    ]

    operations = [
        # Removido RemoveField para user_django porque nunca existió en la base de datos
        # migrations.RemoveField(
        #     model_name='usuario',
        #     name='user_django',
        # ),
        migrations.AlterField(
            model_name='merma',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.RESTRICT, to='inventario.usuario', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.RESTRICT, to='inventario.usuario', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_rol',
            field=models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.RESTRICT, to='inventario.rol', verbose_name='Rol'),
        ),
    ]
