# Generated by Django 5.2.7 on 2025-11-06 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_remove_usuario_user_django_alter_merma_id_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user_django',
        ),
    ]
