# Generated by Django 5.2.7 on 2025-11-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_remove_usuario_user_django'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='codigo',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='lote',
            name='numero_lote',
            field=models.CharField(blank=True, db_column='numero_lote', max_length=50, null=True, verbose_name='Número de Lote'),
        ),
    ]
