# Generated by Django 5.2.7 on 2025-11-10 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_insumo_codigo_lote_numero_lote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatoProducido',
            fields=[
                ('id_plato_producido', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('en_cocina', 'En Cocina'), ('en_mesa', 'En Mesa'), ('entregado', 'Entregado')], default='en_cocina', max_length=20, verbose_name='Estado')),
                ('fecha_produccion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Producción')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('id_plato', models.ForeignKey(db_column='id_plato', on_delete=django.db.models.deletion.RESTRICT, to='inventario.plato', verbose_name='Plato')),
                ('id_ubicacion', models.ForeignKey(db_column='id_ubicacion', on_delete=django.db.models.deletion.RESTRICT, to='inventario.ubicacion', verbose_name='Ubicación')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.RESTRICT, related_name='platos_producidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Plato Producido',
                'verbose_name_plural': 'Platos Producidos',
                'db_table': 'PLATO_PRODUCIDO',
                'ordering': ['-fecha_produccion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleProduccionInsumo',
            fields=[
                ('id_detalle_produccion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_usada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Usada')),
                ('fecha_uso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Uso')),
                ('id_insumo', models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.RESTRICT, to='inventario.insumo', verbose_name='Insumo')),
                ('id_lote', models.ForeignKey(db_column='id_lote', on_delete=django.db.models.deletion.RESTRICT, to='inventario.lote', verbose_name='Lote')),
                ('id_plato_producido', models.ForeignKey(db_column='id_plato_producido', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_insumos', to='inventario.platoproducido', verbose_name='Plato Producido')),
            ],
            options={
                'verbose_name': 'Detalle de Producción de Insumo',
                'verbose_name_plural': 'Detalles de Producción de Insumos',
                'db_table': 'DETALLE_PRODUCCION_INSUMO',
                'ordering': ['-fecha_uso'],
            },
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='origen_movimiento',
            field=models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta'), ('merma', 'Merma'), ('prediccion', 'Predicción'), ('manual', 'Manual'), ('produccion', 'Producción')], max_length=20, verbose_name='Origen del Movimiento'),
        ),
    ]
