# Generated by Django 5.2.7 on 2025-11-10 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_add_plato_producido'),
    ]

    operations = [
        migrations.RunSQL(
            # Agregar 'produccion' al ENUM de origen_movimiento
            sql="ALTER TABLE MOVIMIENTO_STOCK MODIFY COLUMN origen_movimiento ENUM('compra','venta','merma','prediccion','manual','produccion') NOT NULL;",
            reverse_sql="ALTER TABLE MOVIMIENTO_STOCK MODIFY COLUMN origen_movimiento ENUM('compra','venta','merma','prediccion','manual') NOT NULL;"
        ),
    ]
